# Generated by Django 5.0.2 on 2024-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Work Process',
                'verbose_name_plural': 'Work Process',
            },
        ),
        migrations.CreateModel(
            name='WorkProcessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Work Process Item',
                'verbose_name_plural': 'Work Process Items',
            },
        ),
    ]
