# Generated by Django 5.0.2 on 2024-02-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workprocess_workprocessitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprocess',
            name='title',
        ),
    ]
