# Generated by Django 5.0.2 on 2024-02-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='text',
            new_name='message',
        ),
    ]
