# Generated by Django 5.0.2 on 2024-02-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_text_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprocessitem',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
