# Generated by Django 5.0.2 on 2024-02-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_content',
            name='job',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='team_content',
            name='user_name',
            field=models.CharField(max_length=35),
        ),
    ]
