# Generated by Django 5.0.2 on 2024-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_team_content_job_alter_team_content_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_content',
            name='icon',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
