# Generated by Django 5.0.2 on 2024-02-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_team_content_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Pricing_Plans',
                'verbose_name_plural': 'Pricing_Plans',
            },
        ),
    ]
