# Generated by Django 5.0.2 on 2024-02-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pricing_plans_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing_plans',
            options={'verbose_name': 'Pricing_Plan', 'verbose_name_plural': 'Pricing_Plans'},
        ),
    ]
