# Generated by Django 5.0.2 on 2024-02-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pricing_plans_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_header', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('currency', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=25)),
                ('active1', models.CharField(max_length=35)),
                ('active2', models.CharField(max_length=35)),
                ('active3', models.CharField(max_length=35)),
                ('active4', models.CharField(max_length=35)),
                ('active5', models.CharField(max_length=35)),
                ('active6', models.CharField(max_length=35)),
                ('main_button', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Price',
            },
        ),
    ]
