# Generated by Django 5.0.2 on 2024-02-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
