# Generated by Django 5.0.2 on 2024-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_count', models.CharField(max_length=15)),
                ('projects', models.CharField(max_length=20)),
                ('happy_clients_count', models.CharField(max_length=15)),
                ('happy_clients', models.CharField(max_length=20)),
                ('awards_wins_count', models.CharField(max_length=15)),
                ('awards_wins', models.CharField(max_length=20)),
                ('countries_count', models.CharField(max_length=15)),
                ('countries', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
            },
        ),
    ]
