# Generated by Django 5.0.2 on 2024-02-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('read_more', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Blog list',
                'verbose_name_plural': 'Blog lists',
            },
        ),
    ]
