# Generated by Django 5.0.2 on 2024-02-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_blog_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing_plans',
            options={'verbose_name': 'Pricing Plan', 'verbose_name_plural': 'Pricing Plans'},
        ),
        migrations.AlterModelOptions(
            name='team_content',
            options={'verbose_name': 'Team content', 'verbose_name_plural': 'Team contents'},
        ),
        migrations.RenameField(
            model_name='blog_list',
            old_name='image',
            new_name='pictures',
        ),
    ]
